# Numpy Questions

### Q.1) Create a numpy array in python?

In [2]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


### Q.2) Write a program that takes in a NumPy array and returns its mean?

In [8]:
import numpy as np

arr = np.array([1,2,3,4])

sum =0;

for i in range(len(arr)+1):
    sum +=i

print(sum/len(arr))

2.5


### Q.3) Write a program that takes in a NumPy array and returns its shape?

In [17]:
import numpy as np

arr = np.array([[1,4],[2,5]])

print(arr.shape)

(2, 2)


### Q.4) How can we convert a list into numpy array?

In [19]:
l = [[1,2],[3,4]]

print(l,type(l))

arr = np.array(l)
print(arr,type(arr))


[[1, 2], [3, 4]] <class 'list'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


### Q.5) Creates a NumPy array filled with zeros of 3X3 size?

In [23]:
import numpy as np

arr = np.zeros([3,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q.6)  Creates a NumPy array filled with ones of mXn size?

In [24]:
import numpy as np

arr = np.ones([3,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Q.7) Creates a NumPy array filled with random values between 0 and 1.

In [33]:
import numpy as np

arr =np.random.randint(0,1,(3,3)) # 1 st value and 2nd values to place in array and las bracket indicates the size
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Q.8)  Creates a NumPy array with a range of values?

In [40]:
import numpy as np

arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


### Q.9) How to reshape a NumPy array to a new shape?

### Q.10) Computes the sum of all the elements in a NumPy array?

### Q.11) Computes the standard deviation of all the elements in a NumPy array.

### Q.12) Computes the dot product of two NumPy arrays.


### Q.13) Create a 2D NumPy array with shape (3, 3) containing all zeros?

### Q.14) Create a 1D numpy array containing the values from -10 to 10, with a step of 2.


### Q.15) Create a 2D numpy array with shape (3, 3) containing random values between 0 and 1. Then, set all values in the first row to 0.

### Q.16) Create a 1D numpy array containing the values from 0 to 9. Then, create a new array containing the values squared.

### Q.17) Create a 1D numpy array containing the values from 1 to 10. Then, extract all even values from the array.

### Q.18) Create a 1D numpy array containing the values from 1 to 10. Then, extract all odd values from the array.

### Q.19)Create a 2D numpy array with shape (3, 3) containing random values between 0 and 1. Then, compute the mean of each row.

### Q.20) How to split numpy array into 3 parts?
#### arr = np.array([1, 2, 3, 4, 5, 6])